### ISSUE TITLE
Container not found

### ISSUE THREAD

**Issue by danbayliss** [philhawthorne/ha-dockermon#80] opened 2020-11-16 22:22 UTC
Hi
I have a few sensors to check if my Docker containers are running and I know it was working fine 6 months ago but for some reason now when the container is stopped it shows as `unknown` instead of `Not Running`

```
  - platform: rest
    resource: http://192.168.0.3:8126/container/addon_core_duckdns
    name: Duck DNS & SSL
    value_template: '{% if value_json.state == "running" %}Running{% else %}Not Running{% endif %}'
```
I've checked the URL and when stopped HA-dockermon shows `container not found`

Any idea what's wrong?

**Comment by philhawthorne** [comment] 2020-11-16 23:13
Are you using docker compose by chance? Wondering if you're doing a `docker-compose down` which actually destroys the underlying docker container.

When the container is stopped and HA-Dockermon reports `container not found`, on your docker host can you please run `docker ps -a` and see if the container you're querying appears in that output?

**Comment by danbayliss** [comment] 2020-11-16 23:39
The containers are HA Supervisor addons. It looks like HA might have switched to using docker compose now they have a watchdog feature that restarts the container if the addon crashes.

If I press stop in the Supervisor menu the container is not listed when running `docker ps -a` and my rest sensor shows as `unknown`. If press stop in Portainer the container is visible in the docker list and the sensor correctly shows as `Not Running`

If this is by design because they use `docker-compose down` are you able to give any advice on changes to my rest sensor to resolve this? Thanks!

**Comment by philhawthorne** [comment] 2020-11-17 00:59
Unfortunately this is by design.

Because the container is destroyed completely, HA-Dockermon will respond with a `404 Not Found` response, and Home Assistant will return `unknown` as the response coming back from HA-Dockermon is not valid for the rest switch. 

Because `docker-compose down` is being used, it actually destroys the container completely. This means there is no way for HA-Dockermon to restart the container, as it will require a `docker-compose up` to be issued (which HA-Dockermon doesn't support). This means that even if the switch existed in your front-end (and marked as off), flicking it on wouldn't do anything, which might cause confusion.

There's no real change I can give you for your rest sensor. I would even say the way it is working now (by going to the `unknown` state) is better. The best solution would be for the switch to be marked as `unavailable`, but it looks like this feature isn't supported by Home Assistant for rest switches yet.

As an FYI, if you switch over to the `edge` tag and use MQTT discovery, in this case when the container is destroyed, HA-Dockermon will then remove the switch entity completely in Home Assistant when the container gets destroyed. Once again this is by design, as once the container is destroyed the switch entity from Home Assistant can't be controlled.

Hope that helps

**Closed by philhawthorne** 2020-11-17 00:59 UTC
